"""add audit programs

Revision ID: 1094ef170a91
Revises: bfc11a7e6376
Create Date: 2026-09-14 13:38:08.313074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1094ef170a91'
down_revision: Union[str, None] = 'bfc11a7e6376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('processus', sa.String(length=255), nullable=True),
    sa.Column('thematique', sa.String(length=255), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('date_debut_prevue', sa.Date(), nullable=False),
    sa.Column('date_fin_prevue', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_programs')
    # ### end Alembic commands ###
