"""add audit grids and findings

Revision ID: 19eb9f4274ec
Revises: 1094ef170a91
Create Date: 2026-09-14 14:08:25.292864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19eb9f4274ec'
down_revision: Union[str, None] = '1094ef170a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['audit_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_grid_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=500), nullable=False),
    sa.Column('ponderation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['audit_grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('conforme', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('preuves', sa.JSON(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['criteria_id'], ['audit_grid_criteria.id'], ),
    sa.ForeignKeyConstraint(['grid_id'], ['audit_grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_findings')
    op.drop_table('audit_grid_criteria')
    op.drop_table('audit_grids')
    # ### end Alembic commands ###
