"""add training capsules and quiz evaluation

Revision ID: 1e9578e3f3a8
Revises: e4440d11d393
Create Date: 2026-09-09 11:18:25.380408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9578e3f3a8'
down_revision: Union[str, None] = 'e4440d11d393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
