"""add templates and document content

Revision ID: 2a016a280cf3
Revises: 96dc85ea388a
Create Date: 2026-09-03 11:30:00.245894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a016a280cf3'
down_revision: Union[str, None] = '96dc85ea388a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('contenu_structure', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('contenu', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'contenu')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
