"""add nom_signature to signatures

Revision ID: 326f2f3739aa
Revises: 6391c2af291c
Create Date: 2026-09-04 16:12:42.049074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326f2f3739aa'
down_revision: Union[str, None] = '6391c2af291c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_signatures', sa.Column('nom_signature', sa.String(length=150), nullable=True))
    op.execute("UPDATE document_signatures SET nom_signature = 'Signature antérieure' WHERE nom_signature IS NULL")
    op.alter_column('document_signatures', 'nom_signature', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_signatures', 'nom_signature')
    # ### end Alembic commands ###
