"""add adverse event actions

Revision ID: 56c29567aa11
Revises: ea6892e28b65
Create Date: 2026-09-11 12:07:36.836143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c29567aa11'
down_revision: Union[str, None] = 'ea6892e28b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adverse_event_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('echeance', sa.DateTime(), nullable=False),
    sa.Column('priorite', sa.String(length=20), nullable=False),
    sa.Column('criticite', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['adverse_events.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adverse_event_actions')
    # ### end Alembic commands ###
