"""add audit actions and closure

Revision ID: 649fa5d52039
Revises: 19eb9f4274ec
Create Date: 2026-09-14 15:25:19.162495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649fa5d52039'
down_revision: Union[str, None] = '19eb9f4274ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('echeance', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_programs', sa.Column('rapport_verrouille', sa.Boolean(), nullable=True))
    op.execute("UPDATE audit_programs SET rapport_verrouille = false WHERE rapport_verrouille IS NULL")
    op.alter_column('audit_programs', 'rapport_verrouille', nullable=False)
    op.add_column('audit_programs', sa.Column('date_cloture', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_programs', 'date_cloture')
    op.drop_column('audit_programs', 'rapport_verrouille')
    op.drop_table('audit_actions')
    # ### end Alembic commands ###
