"""add adverse events declaration

Revision ID: 7c76ee3220e3
Revises: f2218ce110f2
Create Date: 2026-09-10 12:53:15.322922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c76ee3220e3'
down_revision: Union[str, None] = 'f2218ce110f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adverse_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_suivi', sa.String(length=30), nullable=False),
    sa.Column('date_evenement', sa.DateTime(), nullable=False),
    sa.Column('lieu', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('personnes_impliquees', sa.Text(), nullable=True),
    sa.Column('gravite', sa.String(length=20), nullable=False),
    sa.Column('actions_immediates', sa.Text(), nullable=True),
    sa.Column('declarant_id', sa.Integer(), nullable=False),
    sa.Column('pieces_jointes', sa.JSON(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_declaration', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['declarant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_suivi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adverse_events')
    # ### end Alembic commands ###
