"""add document assignments and perimetre

Revision ID: 96dc85ea388a
Revises: da6ce0c4f144
Create Date: 2026-09-03 10:37:29.861810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dc85ea388a'
down_revision: Union[str, None] = 'da6ce0c4f144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_document', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document_requests', sa.Column('motif_rejet', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('perimetre', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('confidentialite', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'confidentialite')
    op.drop_column('documents', 'perimetre')
    op.drop_column('document_requests', 'motif_rejet')
    op.drop_table('document_assignments')
    # ### end Alembic commands ###
