"""add validation circuits

Revision ID: bb18b094683e
Revises: 1a94db9b931c
Create Date: 2026-09-04 17:19:40.870248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb18b094683e'
down_revision: Union[str, None] = '1a94db9b931c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('role_direction', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_direction', sa.String(length=50), nullable=False),
    sa.Column('nom_signature', sa.String(length=150), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('verrouille', sa.Boolean(), nullable=True))
    op.execute("UPDATE documents SET verrouille = false WHERE verrouille IS NULL")
    op.alter_column('documents', 'verrouille', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'verrouille')
    op.drop_table('document_validations')
    op.drop_table('validation_circuits')
    # ### end Alembic commands ###
