"""add documents tables

Revision ID: da6ce0c4f144
Revises: e8b9d88834bd
Create Date: 2026-09-02 14:52:55.958677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6ce0c4f144'
down_revision: Union[str, None] = 'e8b9d88834bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intitule', sa.String(length=255), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('version_courante', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('demandeur_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('pieces_jointes', sa.JSON(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demandeur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_requests')
    op.drop_table('documents')
    # ### end Alembic commands ###
