"""add official adverse event form fields

Revision ID: e319063e2dcb
Revises: 56c29567aa11
Create Date: 2026-09-14 10:01:20.173354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e319063e2dcb'
down_revision: Union[str, None] = '56c29567aa11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverse_events', sa.Column('professionnel_identifiant', sa.String(length=255), nullable=True))
    op.add_column('adverse_events', sa.Column('contact_professionnel', sa.String(length=255), nullable=True))
    op.add_column('adverse_events', sa.Column('categorie', sa.JSON(), nullable=True))
    op.add_column('adverse_events', sa.Column('signalement_effectue_a', sa.JSON(), nullable=True))
    op.add_column('adverse_events', sa.Column('visa_major', sa.String(length=150), nullable=True))
    op.add_column('adverse_events', sa.Column('date_completion_major', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverse_events', 'date_completion_major')
    op.drop_column('adverse_events', 'visa_major')
    op.drop_column('adverse_events', 'signalement_effectue_a')
    op.drop_column('adverse_events', 'categorie')
    op.drop_column('adverse_events', 'contact_professionnel')
    op.drop_column('adverse_events', 'professionnel_identifiant')
    # ### end Alembic commands ###
