"""add site_id to documents events audits

Revision ID: eda15da90a90
Revises: 649fa5d52039
Create Date: 2026-09-15 11:03:57.221368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda15da90a90'
down_revision: Union[str, None] = '649fa5d52039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverse_events', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'adverse_events', 'sites', ['site_id'], ['id'])
    op.add_column('audit_programs', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audit_programs', 'sites', ['site_id'], ['id'])
    op.add_column('documents', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'sites', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'site_id')
    op.drop_constraint(None, 'audit_programs', type_='foreignkey')
    op.drop_column('audit_programs', 'site_id')
    op.drop_constraint(None, 'adverse_events', type_='foreignkey')
    op.drop_column('adverse_events', 'site_id')
    # ### end Alembic commands ###
