"""add document versioning and revision tracking

Revision ID: f2218ce110f2
Revises: 1e9578e3f3a8
Create Date: 2026-09-09 14:21:34.412295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2218ce110f2'
down_revision: Union[str, None] = '1e9578e3f3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_parent_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('revision_notifiee', sa.Boolean(), nullable=True))
    op.execute("UPDATE documents SET revision_notifiee = false WHERE revision_notifiee IS NULL")
    op.alter_column('documents', 'revision_notifiee', nullable=False)
    op.create_foreign_key(None, 'documents', 'documents', ['document_parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'revision_notifiee')
    op.drop_column('documents', 'document_parent_id')
    # ### end Alembic commands ###
